version: "3.7"

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal

  server:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        GROUP_NAME: ${GROUP_NAME}
    image: server
    container_name: server
    restart: unless-stopped
    volumes:
      - ./source:/var/www
    networks:
      - internal

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - mysql
      - server
    volumes:
      - ./source:/var/www
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - internal

networks:
  internal:
    driver: bridge
